# Nodes package

# Temporarily disabled
# from .preview_bridge import NODE_CLASS_MAPPINGS as PREVIEW_BRIDGE_MAPPINGS
# from .preview_bridge import NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_BRIDGE_DISPLAY_MAPPINGS
from .batch_color_corrector import NODE_CLASS_MAPPINGS as BATCH_COLOR_MAPPINGS
from .batch_color_corrector import NODE_DISPLAY_NAME_MAPPINGS as BATCH_COLOR_DISPLAY_MAPPINGS
from .iterative_video import NODE_CLASS_MAPPINGS as ITER_VIDEO_MAPPINGS
from .iterative_video import NODE_DISPLAY_NAME_MAPPINGS as ITER_VIDEO_DISPLAY_MAPPINGS
from .context_video import NODE_CLASS_MAPPINGS as CONTEXT_VIDEO_MAPPINGS
from .context_video import NODE_DISPLAY_NAME_MAPPINGS as CONTEXT_VIDEO_DISPLAY_MAPPINGS
from .preprocess_settings import NODE_CLASS_MAPPINGS as PREPROCESS_MAPPINGS
from .preprocess_settings import NODE_DISPLAY_NAME_MAPPINGS as PREPROCESS_DISPLAY_MAPPINGS
from .resolution_picker import NODE_CLASS_MAPPINGS as RESOLUTION_MAPPINGS
from .resolution_picker import NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    # **PREVIEW_BRIDGE_MAPPINGS,
    **BATCH_COLOR_MAPPINGS,
    **ITER_VIDEO_MAPPINGS,
    **CONTEXT_VIDEO_MAPPINGS,
    **PREPROCESS_MAPPINGS,
    **RESOLUTION_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    # **PREVIEW_BRIDGE_DISPLAY_MAPPINGS,
    **BATCH_COLOR_DISPLAY_MAPPINGS,
    **ITER_VIDEO_DISPLAY_MAPPINGS,
    **CONTEXT_VIDEO_DISPLAY_MAPPINGS,
    **PREPROCESS_DISPLAY_MAPPINGS,
    **RESOLUTION_DISPLAY_MAPPINGS,
}
