# Nodes package

# Temporarily disabled
# from .preview_bridge import NODE_CLASS_MAPPINGS as PREVIEW_BRIDGE_MAPPINGS
# from .preview_bridge import NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_BRIDGE_DISPLAY_MAPPINGS
from .batch_color_corrector import NODE_CLASS_MAPPINGS as BATCH_COLOR_MAPPINGS
from .batch_color_corrector import NODE_DISPLAY_NAME_MAPPINGS as BATCH_COLOR_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    # **PREVIEW_BRIDGE_MAPPINGS,
    **BATCH_COLOR_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    # **PREVIEW_BRIDGE_DISPLAY_MAPPINGS,
    **BATCH_COLOR_DISPLAY_MAPPINGS,
}
