# Nodes package

# Temporarily disabled
# from .preview_bridge import NODE_CLASS_MAPPINGS as PREVIEW_BRIDGE_MAPPINGS
# from .preview_bridge import NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_BRIDGE_DISPLAY_MAPPINGS
from .batch_color_corrector import NODE_CLASS_MAPPINGS as BATCH_COLOR_MAPPINGS
from .batch_color_corrector import NODE_DISPLAY_NAME_MAPPINGS as BATCH_COLOR_DISPLAY_MAPPINGS
from .iterative_video import NODE_CLASS_MAPPINGS as ITER_VIDEO_MAPPINGS
from .iterative_video import NODE_DISPLAY_NAME_MAPPINGS as ITER_VIDEO_DISPLAY_MAPPINGS
from .context_video import NODE_CLASS_MAPPINGS as CONTEXT_VIDEO_MAPPINGS
from .context_video import NODE_DISPLAY_NAME_MAPPINGS as CONTEXT_VIDEO_DISPLAY_MAPPINGS
from .preprocess_settings import NODE_CLASS_MAPPINGS as PREPROCESS_MAPPINGS
from .preprocess_settings import NODE_DISPLAY_NAME_MAPPINGS as PREPROCESS_DISPLAY_MAPPINGS
from .resolution_picker import NODE_CLASS_MAPPINGS as RESOLUTION_MAPPINGS
from .resolution_picker import NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_DISPLAY_MAPPINGS
from .frame_context_fit import NODE_CLASS_MAPPINGS as FRAME_CONTEXT_MAPPINGS
from .frame_context_fit import NODE_DISPLAY_NAME_MAPPINGS as FRAME_CONTEXT_DISPLAY_MAPPINGS
from .wan_resolution_picker import NODE_CLASS_MAPPINGS as WAN_RESOLUTION_MAPPINGS
from .wan_resolution_picker import NODE_DISPLAY_NAME_MAPPINGS as WAN_RESOLUTION_DISPLAY_MAPPINGS
from .ltx_resolution_picker import NODE_CLASS_MAPPINGS as LTX_RESOLUTION_MAPPINGS
from .ltx_resolution_picker import NODE_DISPLAY_NAME_MAPPINGS as LTX_RESOLUTION_DISPLAY_MAPPINGS
from .clamp_float import NODE_CLASS_MAPPINGS as CLAMP_FLOAT_MAPPINGS
from .clamp_float import NODE_DISPLAY_NAME_MAPPINGS as CLAMP_FLOAT_DISPLAY_MAPPINGS
from .video_concatenate import NODE_CLASS_MAPPINGS as VIDEO_CONCAT_MAPPINGS
from .video_concatenate import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_CONCAT_DISPLAY_MAPPINGS
from .image_exists import NODE_CLASS_MAPPINGS as IMAGE_EXISTS_MAPPINGS
from .image_exists import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_EXISTS_DISPLAY_MAPPINGS
from .data_exists import NODE_CLASS_MAPPINGS as DATA_EXISTS_MAPPINGS
from .data_exists import NODE_DISPLAY_NAME_MAPPINGS as DATA_EXISTS_DISPLAY_MAPPINGS
from .execution_gate import NODE_CLASS_MAPPINGS as EXECUTION_GATE_MAPPINGS
from .execution_gate import NODE_DISPLAY_NAME_MAPPINGS as EXECUTION_GATE_DISPLAY_MAPPINGS
from .free_vram import NODE_CLASS_MAPPINGS as FREE_VRAM_MAPPINGS
from .free_vram import NODE_DISPLAY_NAME_MAPPINGS as FREE_VRAM_DISPLAY_MAPPINGS
from .string_batch import NODE_CLASS_MAPPINGS as STRING_BATCH_MAPPINGS
from .string_batch import NODE_DISPLAY_NAME_MAPPINGS as STRING_BATCH_DISPLAY_MAPPINGS
from .story_style_selector import NODE_CLASS_MAPPINGS as STORY_STYLE_MAPPINGS
from .story_style_selector import NODE_DISPLAY_NAME_MAPPINGS as STORY_STYLE_DISPLAY_MAPPINGS
from .control_crossfade import NODE_CLASS_MAPPINGS as CONTROL_CROSSFADE_MAPPINGS
from .control_crossfade import NODE_DISPLAY_NAME_MAPPINGS as CONTROL_CROSSFADE_DISPLAY_MAPPINGS
from .image_mode_router import NODE_CLASS_MAPPINGS as IMAGE_MODE_ROUTER_MAPPINGS
from .image_mode_router import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_MODE_ROUTER_DISPLAY_MAPPINGS
from .image_fallback import NODE_CLASS_MAPPINGS as IMAGE_FALLBACK_MAPPINGS
from .image_fallback import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_FALLBACK_DISPLAY_MAPPINGS
from .shot_system import NODE_CLASS_MAPPINGS as SHOT_SYSTEM_MAPPINGS
from .shot_system import NODE_DISPLAY_NAME_MAPPINGS as SHOT_SYSTEM_DISPLAY_MAPPINGS
from .lipsync import NODE_CLASS_MAPPINGS as LIPSYNC_MAPPINGS
from .lipsync import NODE_DISPLAY_NAME_MAPPINGS as LIPSYNC_DISPLAY_MAPPINGS
from .bundle import NODE_CLASS_MAPPINGS as BUNDLE_MAPPINGS
from .bundle import NODE_DISPLAY_NAME_MAPPINGS as BUNDLE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    # **PREVIEW_BRIDGE_MAPPINGS,
    **BATCH_COLOR_MAPPINGS,
    **ITER_VIDEO_MAPPINGS,
    **CONTEXT_VIDEO_MAPPINGS,
    **PREPROCESS_MAPPINGS,
    **RESOLUTION_MAPPINGS,
    **FRAME_CONTEXT_MAPPINGS,
    **WAN_RESOLUTION_MAPPINGS,
    **LTX_RESOLUTION_MAPPINGS,
    **CLAMP_FLOAT_MAPPINGS,
    **VIDEO_CONCAT_MAPPINGS,
    **IMAGE_EXISTS_MAPPINGS,
    **DATA_EXISTS_MAPPINGS,
    **EXECUTION_GATE_MAPPINGS,
    **FREE_VRAM_MAPPINGS,
    **STRING_BATCH_MAPPINGS,
    **STORY_STYLE_MAPPINGS,
    **CONTROL_CROSSFADE_MAPPINGS,
    **IMAGE_MODE_ROUTER_MAPPINGS,
    **IMAGE_FALLBACK_MAPPINGS,
    **SHOT_SYSTEM_MAPPINGS,
    **LIPSYNC_MAPPINGS,
    **BUNDLE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    # **PREVIEW_BRIDGE_DISPLAY_MAPPINGS,
    **BATCH_COLOR_DISPLAY_MAPPINGS,
    **ITER_VIDEO_DISPLAY_MAPPINGS,
    **CONTEXT_VIDEO_DISPLAY_MAPPINGS,
    **PREPROCESS_DISPLAY_MAPPINGS,
    **RESOLUTION_DISPLAY_MAPPINGS,
    **FRAME_CONTEXT_DISPLAY_MAPPINGS,
    **WAN_RESOLUTION_DISPLAY_MAPPINGS,
    **LTX_RESOLUTION_DISPLAY_MAPPINGS,
    **CLAMP_FLOAT_DISPLAY_MAPPINGS,
    **VIDEO_CONCAT_DISPLAY_MAPPINGS,
    **IMAGE_EXISTS_DISPLAY_MAPPINGS,
    **DATA_EXISTS_DISPLAY_MAPPINGS,
    **EXECUTION_GATE_DISPLAY_MAPPINGS,
    **FREE_VRAM_DISPLAY_MAPPINGS,
    **STRING_BATCH_DISPLAY_MAPPINGS,
    **STORY_STYLE_DISPLAY_MAPPINGS,
    **CONTROL_CROSSFADE_DISPLAY_MAPPINGS,
    **IMAGE_MODE_ROUTER_DISPLAY_MAPPINGS,
    **IMAGE_FALLBACK_DISPLAY_MAPPINGS,
    **SHOT_SYSTEM_DISPLAY_MAPPINGS,
    **LIPSYNC_DISPLAY_MAPPINGS,
    **BUNDLE_DISPLAY_MAPPINGS,
}
